"""empty message

Revision ID: 2505ed3022f8
Revises: 429fda509388
Create Date: 2020-06-21 12:19:27.061137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2505ed3022f8'
down_revision = '429fda509388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'families', ['family_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'families', type_='unique')
    # ### end Alembic commands ###
