"""empty message

Revision ID: 3cddac28b812
Revises: 
Create Date: 2019-12-08 18:07:05.808803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cddac28b812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=1024), nullable=False))
    op.drop_column('user', 'role')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
