"""Removing healthcare unit table

Revision ID: c282d0a3b27f
Revises: 
Create Date: 2020-10-12 11:11:22.854900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c282d0a3b27f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthcareunits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcareunits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('healthcareunit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='healthcareunits_pkey')
    )
    # ### end Alembic commands ###
