"""empty message

Revision ID: f47538408803
Revises: 2505ed3022f8
Create Date: 2020-07-25 15:08:26.212246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47538408803'
down_revision = '2505ed3022f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('work_schedule', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='schedule_pkey')
    )
    # ### end Alembic commands ###
